version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
      - "1234:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=contacts
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql